route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: 'critical'
      receiver: 'email-alert'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'   # Optional for webhook alerts
  - name: 'email-alert'
    email_configs:
      - to: 'keimayazuto@gmail.com'        # Replace with the recipient's email address
        from: 'keimayazuto@gmail.com'        # Replace with your email address
        smarthost: 'smtp.gmail.com:587'      # Gmail SMTP server
        auth_username: 'keimayazuto@gmail.com'  # Your Gmail address
        auth_password: 'yayk wvmc vbgp nsxs'  # Your Gmail app password
        require_tls: true                    # Use TLS for secure communication

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
 
